@startuml
left header

<font color=000 size=16><b>Назва:</b> Авторизація представника організації.
<font color=000 size=16><b>Учасники:</b> Гість, Система.
<font color=000 size=16><b>Передумови:</b> До цього даний користувач був зареєстрований і має обліковий запис.
<font color=000 size=16><b>Результат:</b> Користувачотримує доступ до його облікового запису.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Користувач с такими даними вже існує
<font color=000 size=16> EX_01: Такої пошти не існує
<font color=000 size=16> EX_02: Код підтвердження введено не вірно

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Гість натискає кнопку "Увійти до облікового запису організації».";
|Система|

: Система отримує запит та надсилає форму для авторизації;

|Користувач|

: Користувач заповнює поля (Логін та Пароль) необхідними даними
і натискає кнопку «Увійти»;


|Система|

: Перевіряє дані на унікальність.;
note right #aaffaa

<font color=red><b> Можливо EX_00.

end note

: Система перевіряє поля на заповненість. 
Перевіряє чи є такий користувач у базі і чи підходить пароль;

note right #aaffaa

<font color=red><b> Можливо EX_00.
<font color=red><b> Можливо EX_01.
<font color=red><b> Можливо EX_02.

end note

: Система надає користувачу доступ до його акаунту;
note right #aaffaa

<font color=red><b> Можливо EX_03.

end note

|Користувач|

: Користувач може вільно користуватись можливостями свого акаунту;


|Користувач|
stop;
@enduml
