@startuml
left header

<font color=000 size=16><b>Назва:</b> Реєстрація представника організації.
<font color=000 size=16><b>Учасники:</b> Незареєстрований користувач(представник організації), Система.
<font color=000 size=16><b>Передумови:</b> До цього даний представник організації не був зареєстрований.
<font color=000 size=16><b>Результат:</b> Обліковий запис представника організації створено.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Користувач с такими даними вже існує
<font color=000 size=16> EX_01: Такої пошти не існує
<font color=000 size=16> EX_02: Код підтвердження введено не вірно

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
:  Натискає кнопку "Реєстрація облікового запису представника";

|Система|
: Система отримує ідентифікатор гостя та надсилає форму для введення електронної пошти;

|Користувач|

: Користувач заповнює форму (ПІБ, електронна пошта);

|Система|

: Перевіряє дані на унікальність.;
note right #aaffaa

<font color=red><b> Можливо EX_00.

end note

: Генерує код підтвердження 
створення облікового запису
Надсилає лист на вказану пошту.;
note right #aaffaa

<font color=red><b> Можливо EX_01.

end note

|Користувач|

: Вводить вказаний в отриманому листі код підтвердження. ;

|Система|

: Перевіряє правильність введеного коду;

note left #aaffaa

<font color=red><b> Можливо EX_02.

end note

: Надсилає форму для внесення інформації про заклад/місце;

|Користувач|

: Заповнює і відправляє форму ;

|Система|

: Перевіряє надану інформацію,
вносить відповідні записи до бази даних;

: Надсилає користувачу дані для входу в обліковий запис;

|Користувач|

: Отримує дані для входу;

stop;
@enduml
